/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 26-bøe-2016 21:14:06 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_UsersActivity_Users]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [UsersActivity] DROP CONSTRAINT [FK_UsersActivity_Users]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_UsersAuthDrivers_Users]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [UsersAuthDrivers] DROP CONSTRAINT [FK_UsersAuthDrivers_Users]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_UsersRole_Users]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [UsersRoles] DROP CONSTRAINT [FK_UsersRole_Users]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_UsersRoles_Roles]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [UsersRoles] DROP CONSTRAINT [FK_UsersRoles_Roles]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Roles]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Roles]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Users]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Users]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[UsersActivity]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [UsersActivity]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[UsersAuthDrivers]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [UsersAuthDrivers]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[UsersRoles]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [UsersRoles]
GO

/* Create Tables */

CREATE TABLE [Roles]
(
	[Role] varchar(30) NOT NULL,
	[RoleName] varchar(100) NULL,
	[Description] text NULL,
	[Deleted] BIT NOT NULL DEFAULT 0
)
GO

CREATE TABLE [Users]
(
	[UserID] int NOT NULL IDENTITY (1, 1),
	[FullName] varchar(255) NULL,
	[UserName] varchar(50) NOT NULL,
	[PwHash] varchar(200) NOT NULL,
	[Email] varchar(255) NOT NULL,
	[Phone] varchar(255) NULL,
	[Title] varchar(50) NULL,
	[Language] varchar(50) NULL,
	[Thumbnail] text NULL,
	[PwToken] varchar(255) NULL,
	[PwTokenExpire] datetime NULL,
	[Created] datetime NULL,
	[LastLogged] datetime NULL,
	[Disabled] BIT NOT NULL DEFAULT 0,
	[Deleted] BIT NOT NULL DEFAULT 0
)
GO

CREATE TABLE [UsersActivity]
(
	[UserActivityID] int NOT NULL IDENTITY (1, 1),
	[UserID] int NOT NULL,
	[IP] varchar(50) NULL,
	[ActivityType] varchar(30) NOT NULL,
	[ActivityDateTime] datetime NOT NULL,
	[Description] text NULL
)
GO

CREATE TABLE [UsersAuthDrivers]
(
	[UserID] int NOT NULL,
	[AuthDriver] varchar(30) NOT NULL,
	[AuthID] varchar(255) NOT NULL
)
GO

CREATE TABLE [UsersRoles]
(
	[UserID] int NOT NULL,
	[Role] varchar(30) NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Roles] 
 ADD CONSTRAINT [PK_Role]
	PRIMARY KEY CLUSTERED ([Role] ASC)
GO

CREATE NONCLUSTERED INDEX [IDX_Deleted] 
 ON [Roles] ([Deleted] ASC)
GO

ALTER TABLE [Users] 
 ADD CONSTRAINT [PK_Users]
	PRIMARY KEY CLUSTERED ([UserID] ASC)
GO

CREATE NONCLUSTERED INDEX [IDX_Deleted] 
 ON [Users] ([Deleted] ASC)
GO

CREATE NONCLUSTERED INDEX [IDX_UserName] 
 ON [Users] ([UserName] ASC)
GO

CREATE NONCLUSTERED INDEX [IDX_PwToken] 
 ON [Users] ([PwToken] ASC)
GO

CREATE NONCLUSTERED INDEX [IDX_Disabled] 
 ON [Users] ([Disabled] ASC)
GO

ALTER TABLE [UsersActivity] 
 ADD CONSTRAINT [PK_UsersActivity]
	PRIMARY KEY CLUSTERED ([UserActivityID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_UsersActivity_Users] 
 ON [UsersActivity] ([UserID] ASC)
GO

CREATE NONCLUSTERED INDEX [IDX_ActivityDateTime] 
 ON [UsersActivity] ([ActivityDateTime] ASC)
GO

CREATE NONCLUSTERED INDEX [IDX_ActivityType] 
 ON [UsersActivity] ([ActivityType] ASC)
GO

CREATE NONCLUSTERED INDEX [IDX_IP] 
 ON [UsersActivity] ([IP] ASC)
GO

ALTER TABLE [UsersAuthDrivers] 
 ADD CONSTRAINT [PK_UsersAuthDrivers]
	PRIMARY KEY CLUSTERED ([UserID] ASC,[AuthDriver] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_UsersAuthDrivers_Users] 
 ON [UsersAuthDrivers] ([UserID] ASC)
GO

CREATE NONCLUSTERED INDEX [IDX_AuthID] 
 ON [UsersAuthDrivers] ([AuthID] ASC)
GO

ALTER TABLE [UsersRoles] 
 ADD CONSTRAINT [PK_UsersRole]
	PRIMARY KEY CLUSTERED ([UserID] ASC,[Role] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_UsersRole_Users] 
 ON [UsersRoles] ([UserID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_UsersRoles_Roles] 
 ON [UsersRoles] ([Role] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [UsersActivity] ADD CONSTRAINT [FK_UsersActivity_Users]
	FOREIGN KEY ([UserID]) REFERENCES [Users] ([UserID]) ON DELETE Cascade ON UPDATE Cascade
GO

ALTER TABLE [UsersAuthDrivers] ADD CONSTRAINT [FK_UsersAuthDrivers_Users]
	FOREIGN KEY ([UserID]) REFERENCES [Users] ([UserID]) ON DELETE Cascade ON UPDATE Cascade
GO

ALTER TABLE [UsersRoles] ADD CONSTRAINT [FK_UsersRole_Users]
	FOREIGN KEY ([UserID]) REFERENCES [Users] ([UserID]) ON DELETE Cascade ON UPDATE Cascade
GO

ALTER TABLE [UsersRoles] ADD CONSTRAINT [FK_UsersRoles_Roles]
	FOREIGN KEY ([Role]) REFERENCES [Roles] ([Role]) ON DELETE Cascade ON UPDATE Cascade
GO
