/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 26-bøe-2016 0:07:53 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `Roles` CASCADE
;

DROP TABLE IF EXISTS `Users` CASCADE
;

DROP TABLE IF EXISTS `UsersActivity` CASCADE
;

DROP TABLE IF EXISTS `UsersAuthDrivers` CASCADE
;

DROP TABLE IF EXISTS `UsersRoles` CASCADE
;

/* Create Tables */

CREATE TABLE `Roles`
(
	`Role` VARCHAR(30) NOT NULL,
	`RoleName` VARCHAR(100) 	 NULL,
	`Description` TEXT 	 NULL,
	`Deleted` BIT(1) NOT NULL DEFAULT 0,
	CONSTRAINT `PK_Role` PRIMARY KEY (`Role` ASC)
)

;

CREATE TABLE `Users`
(
	`UserID` INTEGER NOT NULL AUTO_INCREMENT,
	`FullName` VARCHAR(255) 	 NULL,
	`UserName` VARCHAR(50) NOT NULL,
	`PwHash` VARCHAR(200) NOT NULL,
	`Email` VARCHAR(255) NOT NULL,
	`Phone` VARCHAR(255) 	 NULL,
	`PwToken` VARCHAR(255) 	 NULL,
	`PwTokenExpire` DATETIME 	 NULL,
	`Created` DATETIME 	 NULL,
	`LastLogged` DATETIME 	 NULL,
	`Disabled` BIT(1) NOT NULL DEFAULT 0,
	`Deleted` BIT(1) NOT NULL DEFAULT 0,
	CONSTRAINT `PK_Users` PRIMARY KEY (`UserID` ASC)
)

;

CREATE TABLE `UsersActivity`
(
	`UserActivityID` INTEGER NOT NULL AUTO_INCREMENT,
	`UserID` INTEGER NOT NULL,
	`IP` VARCHAR(50) 	 NULL,
	`ActivityType` VARCHAR(30) NOT NULL,
	`ActivityDateTime` DATETIME NOT NULL,
	`Description` TEXT 	 NULL,
	CONSTRAINT `PK_UsersActivity` PRIMARY KEY (`UserActivityID` ASC)
)

;

CREATE TABLE `UsersAuthDrivers`
(
	`UserID` INTEGER NOT NULL,
	`AuthDriver` VARCHAR(30) NOT NULL,
	`AuthID` VARCHAR(255) NOT NULL,
	CONSTRAINT `PK_UsersAuthDrivers` PRIMARY KEY (`UserID` ASC, `AuthDriver` ASC)
)

;

CREATE TABLE `UsersRoles`
(
	`UserID` INTEGER NOT NULL,
	`Role` VARCHAR(30) NOT NULL,
	CONSTRAINT `PK_UsersRole` PRIMARY KEY (`UserID` ASC, `Role` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `Roles` 
 ADD INDEX `IDX_Deleted` (`Deleted` ASC)
;

ALTER TABLE `Users` 
 ADD INDEX `IDX_Deleted` (`Deleted` ASC)
;

ALTER TABLE `Users` 
 ADD INDEX `IDX_UserName` (`UserName` ASC)
;

ALTER TABLE `Users` 
 ADD INDEX `IDX_PwToken` (`PwToken` ASC)
;

ALTER TABLE `Users` 
 ADD INDEX `IDX_Disabled` (`Disabled` ASC)
;

ALTER TABLE `UsersActivity` 
 ADD INDEX `IXFK_UsersActivity_Users` (`UserID` ASC)
;

ALTER TABLE `UsersActivity` 
 ADD INDEX `IDX_ActivityDateTime` (`ActivityDateTime` ASC)
;

ALTER TABLE `UsersActivity` 
 ADD INDEX `IDX_ActivityType` (`ActivityType` ASC)
;

ALTER TABLE `UsersActivity` 
 ADD INDEX `IDX_IP` (`IP` ASC)
;

ALTER TABLE `UsersAuthDrivers` 
 ADD INDEX `IXFK_UsersAuthDrivers_Users` (`UserID` ASC)
;

ALTER TABLE `UsersAuthDrivers` 
 ADD INDEX `IXFK_UsersAuthDrivers_Users_02` (`UserID` ASC)
;

ALTER TABLE `UsersAuthDrivers` 
 ADD INDEX `IDX_AuthID` (`AuthID` ASC)
;

ALTER TABLE `UsersRoles` 
 ADD INDEX `IXFK_UsersRole_Role` (`Role` ASC)
;

ALTER TABLE `UsersRoles` 
 ADD INDEX `IXFK_UsersRole_Users` (`UserID` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `UsersActivity` 
 ADD CONSTRAINT `FK_UsersActivity_Users`
	FOREIGN KEY (`UserID`) REFERENCES `Users` (`UserID`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `UsersAuthDrivers` 
 ADD CONSTRAINT `FK_UsersAuthDrivers_Users`
	FOREIGN KEY (`UserID`) REFERENCES  () ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `UsersAuthDrivers` 
 ADD CONSTRAINT `FK_UsersAuthDrivers_Users_02`
	FOREIGN KEY (`UserID`) REFERENCES `Users` (`UserID`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `UsersRoles` 
 ADD CONSTRAINT `FK_UsersRole_Role`
	FOREIGN KEY (`Role`) REFERENCES `Roles` (`Role`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `UsersRoles` 
 ADD CONSTRAINT `FK_UsersRole_Users`
	FOREIGN KEY (`UserID`) REFERENCES `Users` (`UserID`) ON DELETE Cascade ON UPDATE Cascade
;

SET FOREIGN_KEY_CHECKS=1 
;
